.codeclimate.yml, .flake8, .pre-commit-config.yaml, .travis.yml, requirements-dev.txt, travis/before-install.sh, travis/test-script.sh
This should add the pre-commit and travis configurations.
=> add travis and some other pre-commit fun things

.travis.yml, README.md, config/example.ini, requirements-dev.txt, requirements.txt, tests/__init__.py, tests/methods_test.py, travis/before-install.sh, travis/unit-tests.sh, travis/uploader.json, uploader_cli/__init__.py, uploader_cli/methods.py, uploader_cli/query.py, uploader_cli/upload.py, uploader_cli/utils.py
This should add the initial CLI argument parsing logic
=> Add initial cli

README.md
Add an install section of the README file.
N/A
=> add install section for README

README.md
This adds some docs on how to run the uploader.
N/A
=> fix readme to include some example interactions

travis/uploader.json, uploader_cli/methods.py, uploader_cli/upload.py
Add the directory prefix options in the metadata configuration
N/A
=> Add directory prefix logic to the uploader

travis/ingest/server.conf, uploader_cli/upload.py
The file obj needs to be faked so we can not genreate a chunked
post for the data.
N/A
=> we need to add a fake file obj to stream right

.pre-commit-config.yaml, CLIUploader.py, requirements-dev.txt, setup.py, tests/__init__.py, tests/methods_test.py, travis/before-install.sh, travis/static-analysis.sh, uploader_cli/__init__.py, uploader_cli/configure.py, uploader_cli/methods.py, uploader_cli/query.py, uploader_cli/upload.py, uploader_cli/utils.py
add updated pre-commit and setuptools scm
N/A
=> add new pre-commit and setuptools scm

Dockerfile, README.md, entrypoint.sh, requirements-dev.txt
[Describe what this change achieves]
[List any existing issues this PR resolves]
=> Add Dockerfile and Entrypoint

Dockerfile, entrypoint.sh
[Describe what this change achieves]
[List any existing issues this PR resolves]
=> minor fixes for uploader to make entrypoint work

appveyor.yml, pacifica/cli/__main__.py, pacifica/cli/upload.py, pacifica/cli/utils.py, travis/unit-tests.sh
This option adds compression to the local save option and users can choose between lzma, bzip2 and gzip.
N/A
=> add compress local save option

docs/cli.configure.rst, docs/cli.methods.rst, docs/cli.query.rst, docs/cli.rst, docs/cli.upload.rst, docs/cli.utils.rst, docs/conf.py
This adds appropriate sphinx configurations to document special
members of the classes (__init__).
N/A
=> Add documenting special members

LICENSE
=> Fix license should be LGPL

.travis.yml, Dockerfile, docker-compose.yml, entrypoint.sh, pacifica/cli/methods.py
This adds some extra environment variable access for settings to
allow the docker container to work better. This also tests the
containers against a running Pacifica (almost all of it).
N/A
=> add docker testing

docker-compose.yml, entrypoint.sh, pacifica/cli/__main__.py
This makes the help output more descriptive describing what the
options are.
Fix #35
=> Better help output for local compression

docs/exampleusage.md
This fixes the documentation to use obvious test file to upload.
Fix #30
=> Use a better file for example upload

docs/configuration.md
The documentation for the user configuration directory was wrong
I'm fixing the documentation to match the code.
Fix #29
=> Fix configuration directory

appveyor.yml, pacifica/cli/methods.py
Modifies constructor and instance method calls in "download" method of `pacifica.cli.methods` module to resolve breaking changes introduced by https://github.com/pacifica/pacifica-python-downloader/pull/14 and https://github.com/pacifica/pacifica-python-downloader/pull/15.
n/a
=> Modify constructor and instance method calls in "download" method

.pre-commit-config.yaml, appveyor.yml, docs/_static/uploader.json, docs/exampleusage.md, travis/unit-tests.sh, travis/uploader.json
This renames proposal to project across the repository.
N/A
=> Rename Proposal to Project

pacifica/cli/configure.py, pacifica/cli/methods.py, requirements-dev.txt, travis/unit-tests.sh
WIP: Basic Auth password from env variable if present instead of config file.
Fix #55
=> #55 Basic Auth Env variables

pacifica/cli/methods.py, pacifica/cli/query.py, pacifica/cli/upload.py, pacifica/cli/utils.py, requirements-dev.txt, tests/methods_test.py
This updates Pylint to 2.0+ and associated changes in the code.
N/A
=> Update Pylint 2.0+

pacifica/cli/__main__.py, pacifica/cli/_version.py
This should add a version module and parse args options to print
the version of the package.
N/A
=> Add Version Module

CHANGELOG.md
- Pull #73 Add Python 3.7 and 3.8 by [dmlb2000](https://github.com/dmlb2000)
- Pull #70 Add Version Moodule by [dmlb2000](https://github.com/dmlb2000)
- Pull #68 Add JSONSchema Validation by [dmlb2000](https://github.com/dmlb2000)
- Pull #66 Add Kerberos/GSSAPI Authentication by [dmlb2000](https://github.com/dmlb2000)
- Fix #55 Add Basic Authentication Env Vars by [casey-pnnl](https://github.com/casey-pnnl)
- Fix #52 Add File Not Found Error by [dmlb2000](https://github.com/dmlb2000)
- Fix #56 Resolve User Logon Always by [dmlb2000](https://github.com/dmlb2000)
- Fix #53 Add Env/CLI for config.ini by [dmlb2000](https://github.com/dmlb2000)
- Fix #61 Do not save during global read by [dmlb2000](https://github.com/dmlb2000)
- Pull #67 Add Ansible to Travis CI by …
=> v0.5.0: Features and Support Fixes

CHANGELOG.md
- Pull #77 Remove Requirements Pip>=20 by [dmlb2000](https://github.com/dmlb2000)
N/A
=> v0.5.1: Packaging and Pipeline Fixes

pacifica/cli/__main__.py
This adds an argv argument to main so it can be called from other
processes.
N/A
=> Add Argv to Main
